platform :ios, '8.0'

target 'Continote' do
  use_frameworks!

  # Firebase (https://github.com/firebase/firebase-ios-sdk)
  pod 'Firebase/Auth', '~> 4.0'
  pod 'Firebase/Database', '~> 4.0'

  # FirebaseUI (https://github.com/firebase/FirebaseUI-iOS)
  pod 'FirebaseUI/Auth', '~> 4.0'
  pod 'FirebaseUI/Database', '~> 4.0'
  pod 'FirebaseUI/Google', '~> 4.0'
  pod 'FirebaseUI/Facebook', '~> 4.0'

  # Material Components (https://github.com/material-components/material-components-ios/)
  pod 'MaterialComponents/AppBar', '~> 31.0'
  pod 'MaterialComponents/AppBar/ColorThemer', '~> 31.0'
  pod 'MaterialComponents/Buttons', '~> 31.0'
  pod 'MaterialComponents/Buttons/ColorThemer', '~> 31.0'
  pod 'MaterialComponents/Snackbar', '~> 31.0'
  pod 'MaterialComponents/TextFields', '~> 31.0'
  pod 'MaterialComponents/Typography', '~> 31.0'

end
